// Comprehensive Mock Data for Demo Mode

// =====================
// MASTER DATA
// =====================

export const mockSeasons = [
  {
    id: 'season-1',
    name: 'Spring/Summer 2025',
    code: 'SS25',
    startDate: new Date('2025-02-01'),
    endDate: new Date('2025-07-31'),
    isCurrent: true,
    isActive: true,
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'season-2',
    name: 'Fall/Winter 2025',
    code: 'FW25',
    startDate: new Date('2025-08-01'),
    endDate: new Date('2026-01-31'),
    isCurrent: false,
    isActive: true,
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'season-3',
    name: 'Fall/Winter 2024',
    code: 'FW24',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2025-01-31'),
    isCurrent: false,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockBrands = [
  {
    id: 'brand-1',
    name: 'Nike',
    code: 'NK',
    description: 'Just Do It - Athletic footwear and apparel',
    logo: null,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-2',
    name: 'Adidas',
    code: 'AD',
    description: 'Impossible Is Nothing - Sports and lifestyle',
    logo: null,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-3',
    name: 'Puma',
    code: 'PM',
    description: 'Forever Faster - Sports brand',
    logo: null,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-4',
    name: 'New Balance',
    code: 'NB',
    description: 'Fearlessly Independent Since 1906',
    logo: null,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'brand-5',
    name: 'Converse',
    code: 'CV',
    description: 'Shoes Are Boring. Wear Sneakers.',
    logo: null,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockCategories = [
  {
    id: 'cat-1',
    name: 'Footwear',
    code: 'FW',
    description: 'All types of shoes and footwear',
    parentId: null,
    level: 0,
    isActive: true,
    children: [
      { id: 'cat-1-1', name: 'Running Shoes', code: 'FW-RUN', parentId: 'cat-1', level: 1, isActive: true },
      { id: 'cat-1-2', name: 'Casual Shoes', code: 'FW-CAS', parentId: 'cat-1', level: 1, isActive: true },
      { id: 'cat-1-3', name: 'Sports Shoes', code: 'FW-SPT', parentId: 'cat-1', level: 1, isActive: true },
    ],
  },
  {
    id: 'cat-2',
    name: 'Apparel',
    code: 'AP',
    description: 'Clothing and apparel items',
    parentId: null,
    level: 0,
    isActive: true,
    children: [
      { id: 'cat-2-1', name: 'T-Shirts', code: 'AP-TSH', parentId: 'cat-2', level: 1, isActive: true },
      { id: 'cat-2-2', name: 'Jackets', code: 'AP-JKT', parentId: 'cat-2', level: 1, isActive: true },
      { id: 'cat-2-3', name: 'Pants', code: 'AP-PNT', parentId: 'cat-2', level: 1, isActive: true },
      { id: 'cat-2-4', name: 'Shorts', code: 'AP-SHT', parentId: 'cat-2', level: 1, isActive: true },
    ],
  },
  {
    id: 'cat-3',
    name: 'Accessories',
    code: 'AC',
    description: 'Bags, caps, and accessories',
    parentId: null,
    level: 0,
    isActive: true,
    children: [
      { id: 'cat-3-1', name: 'Bags', code: 'AC-BAG', parentId: 'cat-3', level: 1, isActive: true },
      { id: 'cat-3-2', name: 'Caps', code: 'AC-CAP', parentId: 'cat-3', level: 1, isActive: true },
      { id: 'cat-3-3', name: 'Socks', code: 'AC-SOC', parentId: 'cat-3', level: 1, isActive: true },
    ],
  },
];

export const mockLocations = [
  {
    id: 'loc-1',
    name: 'Ho Chi Minh City',
    code: 'HCM',
    type: 'REGION',
    address: 'District 1, Ho Chi Minh City',
    isActive: true,
    parentId: null,
  },
  {
    id: 'loc-2',
    name: 'Hanoi',
    code: 'HN',
    type: 'REGION',
    address: 'Hoan Kiem District, Hanoi',
    isActive: true,
    parentId: null,
  },
  {
    id: 'loc-3',
    name: 'Da Nang',
    code: 'DN',
    type: 'REGION',
    address: 'Hai Chau District, Da Nang',
    isActive: true,
    parentId: null,
  },
  {
    id: 'loc-4',
    name: 'Vincom HCM',
    code: 'VIN-HCM',
    type: 'STORE',
    address: 'Vincom Center, District 1, HCM',
    isActive: true,
    parentId: 'loc-1',
  },
  {
    id: 'loc-5',
    name: 'Aeon Mall HCM',
    code: 'AEON-HCM',
    type: 'STORE',
    address: 'Aeon Mall Tan Phu, HCM',
    isActive: true,
    parentId: 'loc-1',
  },
  {
    id: 'loc-6',
    name: 'Vincom Hanoi',
    code: 'VIN-HN',
    type: 'STORE',
    address: 'Vincom Ba Trieu, Hanoi',
    isActive: true,
    parentId: 'loc-2',
  },
  {
    id: 'loc-7',
    name: 'Lotte Hanoi',
    code: 'LOT-HN',
    type: 'STORE',
    address: 'Lotte Center, Hanoi',
    isActive: true,
    parentId: 'loc-2',
  },
  {
    id: 'loc-8',
    name: 'Indochina Da Nang',
    code: 'IND-DN',
    type: 'STORE',
    address: 'Indochina Riverside, Da Nang',
    isActive: true,
    parentId: 'loc-3',
  },
];

export const mockUsers = [
  {
    id: 'user-1',
    email: 'admin@dafc.com',
    name: 'Admin User',
    role: 'ADMIN',
    status: 'ACTIVE',
    avatar: null,
    department: 'IT',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    email: 'planner@dafc.com',
    name: 'OTB Planner',
    role: 'PLANNER',
    status: 'ACTIVE',
    avatar: null,
    department: 'Planning',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-3',
    email: 'manager@dafc.com',
    name: 'Brand Manager',
    role: 'BRAND_MANAGER',
    status: 'ACTIVE',
    avatar: null,
    department: 'Brand Management',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-4',
    email: 'buyer@dafc.com',
    name: 'Buyer User',
    role: 'BUYER',
    status: 'ACTIVE',
    avatar: null,
    department: 'Purchasing',
    createdAt: new Date('2024-01-01'),
  },
];

// =====================
// BUDGET DATA
// =====================

export const mockBudgets = [
  {
    id: 'budget-1',
    seasonId: 'season-1',
    brandId: 'brand-1',
    locationId: 'loc-1',
    totalBudget: 5000000000,
    allocatedBudget: 4500000000,
    remainingBudget: 500000000,
    status: 'APPROVED',
    version: 1,
    notes: 'Main budget for Nike SS25 in HCM region',
    createdById: 'user-2',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-15'),
    season: mockSeasons[0],
    brand: mockBrands[0],
    location: mockLocations[0],
    createdBy: mockUsers[1],
  },
  {
    id: 'budget-2',
    seasonId: 'season-1',
    brandId: 'brand-2',
    locationId: 'loc-1',
    totalBudget: 4000000000,
    allocatedBudget: 3200000000,
    remainingBudget: 800000000,
    status: 'APPROVED',
    version: 1,
    notes: 'Adidas SS25 budget for HCM',
    createdById: 'user-2',
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-20'),
    season: mockSeasons[0],
    brand: mockBrands[1],
    location: mockLocations[0],
    createdBy: mockUsers[1],
  },
  {
    id: 'budget-3',
    seasonId: 'season-1',
    brandId: 'brand-1',
    locationId: 'loc-2',
    totalBudget: 3500000000,
    allocatedBudget: 2800000000,
    remainingBudget: 700000000,
    status: 'SUBMITTED',
    version: 1,
    notes: 'Nike SS25 budget for Hanoi region',
    createdById: 'user-2',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-25'),
    season: mockSeasons[0],
    brand: mockBrands[0],
    location: mockLocations[1],
    createdBy: mockUsers[1],
  },
  {
    id: 'budget-4',
    seasonId: 'season-1',
    brandId: 'brand-3',
    locationId: 'loc-1',
    totalBudget: 2500000000,
    allocatedBudget: 0,
    remainingBudget: 2500000000,
    status: 'DRAFT',
    version: 1,
    notes: 'Puma SS25 budget draft',
    createdById: 'user-2',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
    season: mockSeasons[0],
    brand: mockBrands[2],
    location: mockLocations[0],
    createdBy: mockUsers[1],
  },
  {
    id: 'budget-5',
    seasonId: 'season-2',
    brandId: 'brand-1',
    locationId: 'loc-1',
    totalBudget: 6000000000,
    allocatedBudget: 0,
    remainingBudget: 6000000000,
    status: 'DRAFT',
    version: 1,
    notes: 'Nike FW25 planning budget',
    createdById: 'user-2',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-11-15'),
    season: mockSeasons[1],
    brand: mockBrands[0],
    location: mockLocations[0],
    createdBy: mockUsers[1],
  },
];

// =====================
// OTB PLANS DATA
// =====================

export const mockOTBLineItems = [
  // OTB Plan 1 - Nike HCM SS25
  {
    id: 'line-1-1',
    otbPlanId: 'otb-1',
    categoryId: 'cat-1',
    gender: 'MEN',
    level: 1,
    userUnits: 5000,
    userBuyValue: 1500000000,
    userBuyPct: 33.33,
    historicalSalesPct: 30,
    historicalSalesValue: 1400000000,
    systemProposedPct: 32,
    systemProposedValue: 1440000000,
    varianceFromSystem: 4.17,
    varianceFromHist: 7.14,
    hasAnomaly: false,
    isLocked: false,
    comment: null,
    category: { id: 'cat-1', name: 'Footwear', code: 'FW' },
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'line-1-2',
    otbPlanId: 'otb-1',
    categoryId: 'cat-1',
    gender: 'WOMEN',
    level: 1,
    userUnits: 4000,
    userBuyValue: 1200000000,
    userBuyPct: 26.67,
    historicalSalesPct: 25,
    historicalSalesValue: 1125000000,
    systemProposedPct: 26,
    systemProposedValue: 1170000000,
    varianceFromSystem: 2.56,
    varianceFromHist: 6.67,
    hasAnomaly: false,
    isLocked: false,
    comment: null,
    category: { id: 'cat-1', name: 'Footwear', code: 'FW' },
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'line-1-3',
    otbPlanId: 'otb-1',
    categoryId: 'cat-2',
    gender: 'MEN',
    level: 1,
    userUnits: 8000,
    userBuyValue: 800000000,
    userBuyPct: 17.78,
    historicalSalesPct: 18,
    historicalSalesValue: 810000000,
    systemProposedPct: 18,
    systemProposedValue: 810000000,
    varianceFromSystem: -1.23,
    varianceFromHist: -1.23,
    hasAnomaly: false,
    isLocked: false,
    comment: null,
    category: { id: 'cat-2', name: 'Apparel', code: 'AP' },
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'line-1-4',
    otbPlanId: 'otb-1',
    categoryId: 'cat-2',
    gender: 'WOMEN',
    level: 1,
    userUnits: 6000,
    userBuyValue: 600000000,
    userBuyPct: 13.33,
    historicalSalesPct: 14,
    historicalSalesValue: 630000000,
    systemProposedPct: 14,
    systemProposedValue: 630000000,
    varianceFromSystem: -4.76,
    varianceFromHist: -4.76,
    hasAnomaly: false,
    isLocked: false,
    comment: null,
    category: { id: 'cat-2', name: 'Apparel', code: 'AP' },
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'line-1-5',
    otbPlanId: 'otb-1',
    categoryId: 'cat-3',
    gender: 'UNISEX',
    level: 1,
    userUnits: 10000,
    userBuyValue: 400000000,
    userBuyPct: 8.89,
    historicalSalesPct: 10,
    historicalSalesValue: 450000000,
    systemProposedPct: 10,
    systemProposedValue: 450000000,
    varianceFromSystem: -11.11,
    varianceFromHist: -11.11,
    hasAnomaly: true,
    anomalyType: 'LOWER_THAN_HISTORICAL',
    isLocked: false,
    comment: 'Reduced accessories allocation for SS25',
    category: { id: 'cat-3', name: 'Accessories', code: 'AC' },
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
];

export const mockOTBPlans = [
  {
    id: 'otb-1',
    budgetId: 'budget-1',
    seasonId: 'season-1',
    brandId: 'brand-1',
    versionName: 'Nike SS25 HCM - Main Plan',
    versionType: 'V0_SYSTEM',
    version: 1,
    status: 'APPROVED',
    totalOTBValue: 4500000000,
    totalSKUCount: 33000,
    comments: 'Initial OTB plan for Nike SS25 season',
    aiConfidenceScore: 0.85,
    createdById: 'user-2',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-11-01'),
    budget: mockBudgets[0],
    createdBy: mockUsers[1],
    lineItems: mockOTBLineItems.filter(l => l.otbPlanId === 'otb-1'),
    _count: { lineItems: 5 },
  },
  {
    id: 'otb-2',
    budgetId: 'budget-2',
    seasonId: 'season-1',
    brandId: 'brand-2',
    versionName: 'Adidas SS25 HCM - Initial',
    versionType: 'V0_SYSTEM',
    version: 1,
    status: 'SUBMITTED',
    totalOTBValue: 3200000000,
    totalSKUCount: 25000,
    comments: 'Adidas initial plan',
    aiConfidenceScore: 0.82,
    createdById: 'user-2',
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-11-05'),
    budget: mockBudgets[1],
    createdBy: mockUsers[1],
    lineItems: [],
    _count: { lineItems: 0 },
  },
  {
    id: 'otb-3',
    budgetId: 'budget-1',
    seasonId: 'season-1',
    brandId: 'brand-1',
    versionName: 'Nike SS25 HCM - Revised',
    versionType: 'REVISED',
    version: 2,
    status: 'DRAFT',
    totalOTBValue: 4800000000,
    totalSKUCount: 35000,
    comments: 'Revised plan with increased footwear allocation',
    aiConfidenceScore: null,
    createdById: 'user-2',
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-11-10'),
    budget: mockBudgets[0],
    createdBy: mockUsers[1],
    lineItems: [],
    _count: { lineItems: 0 },
  },
];

// =====================
// SKU PROPOSALS DATA
// =====================

export const mockSKUItems = [
  {
    id: 'sku-item-1',
    proposalId: 'sku-1',
    sku: 'NK-AM90-BLK-42',
    productName: 'Air Max 90 Black',
    categoryId: 'cat-1-1',
    gender: 'MEN',
    color: 'Black/White',
    size: '42',
    costPrice: 2200000,
    retailPrice: 3990000,
    quantity: 150,
    totalCost: 330000000,
    totalRetail: 598500000,
    marginPercent: 44.86,
    status: 'APPROVED',
    aiScore: 92,
    aiRecommendation: 'High demand expected based on historical data',
  },
  {
    id: 'sku-item-2',
    proposalId: 'sku-1',
    sku: 'NK-AM90-WHT-42',
    productName: 'Air Max 90 White',
    categoryId: 'cat-1-1',
    gender: 'MEN',
    color: 'White/Red',
    size: '42',
    costPrice: 2200000,
    retailPrice: 3990000,
    quantity: 120,
    totalCost: 264000000,
    totalRetail: 478800000,
    marginPercent: 44.86,
    status: 'APPROVED',
    aiScore: 88,
    aiRecommendation: 'Strong performer in previous seasons',
  },
  {
    id: 'sku-item-3',
    proposalId: 'sku-1',
    sku: 'NK-DRI-TSH-BLK-M',
    productName: 'Dri-FIT T-Shirt',
    categoryId: 'cat-2-1',
    gender: 'MEN',
    color: 'Black',
    size: 'M',
    costPrice: 350000,
    retailPrice: 690000,
    quantity: 500,
    totalCost: 175000000,
    totalRetail: 345000000,
    marginPercent: 49.28,
    status: 'APPROVED',
    aiScore: 95,
    aiRecommendation: 'Best seller, recommend increasing quantity',
  },
  {
    id: 'sku-item-4',
    proposalId: 'sku-1',
    sku: 'NK-WND-JKT-NVY-L',
    productName: 'Windrunner Jacket Navy',
    categoryId: 'cat-2-2',
    gender: 'UNISEX',
    color: 'Navy Blue',
    size: 'L',
    costPrice: 890000,
    retailPrice: 1690000,
    quantity: 200,
    totalCost: 178000000,
    totalRetail: 338000000,
    marginPercent: 47.34,
    status: 'PENDING',
    aiScore: 78,
    aiRecommendation: 'Moderate demand, consider seasonal timing',
  },
];

export const mockSKUProposals = [
  {
    id: 'sku-1',
    otbPlanId: 'otb-1',
    name: 'Nike SS25 HCM - SKU Batch 1',
    status: 'APPROVED',
    totalSKUs: 45,
    totalQuantity: 5200,
    totalCost: 2800000000,
    totalRetail: 5100000000,
    avgMargin: 45.1,
    validationStatus: 'PASSED',
    validationErrors: [],
    createdById: 'user-4',
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-15'),
    otbPlan: mockOTBPlans[0],
    createdBy: mockUsers[3],
    items: mockSKUItems,
  },
  {
    id: 'sku-2',
    otbPlanId: 'otb-1',
    name: 'Nike SS25 HCM - SKU Batch 2',
    status: 'SUBMITTED',
    totalSKUs: 32,
    totalQuantity: 3800,
    totalCost: 1700000000,
    totalRetail: 3100000000,
    avgMargin: 45.16,
    validationStatus: 'PASSED',
    validationErrors: [],
    createdById: 'user-4',
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-11-18'),
    otbPlan: mockOTBPlans[0],
    createdBy: mockUsers[3],
    items: [],
  },
  {
    id: 'sku-3',
    otbPlanId: 'otb-2',
    name: 'Adidas SS25 - Initial SKUs',
    status: 'DRAFT',
    totalSKUs: 0,
    totalQuantity: 0,
    totalCost: 0,
    totalRetail: 0,
    avgMargin: 0,
    validationStatus: 'PENDING',
    validationErrors: [],
    createdById: 'user-4',
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-11-20'),
    otbPlan: mockOTBPlans[1],
    createdBy: mockUsers[3],
    items: [],
  },
];

// =====================
// WORKFLOWS & APPROVALS
// =====================

export const mockWorkflows = [
  {
    id: 'wf-1',
    type: 'BUDGET_APPROVAL',
    referenceType: 'BUDGET',
    referenceId: 'budget-3',
    status: 'IN_PROGRESS',
    currentStep: 1,
    totalSteps: 2,
    initiatedById: 'user-2',
    initiatedBy: mockUsers[1],
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-10-25'),
    steps: [
      {
        id: 'step-1-1',
        stepNumber: 1,
        stepName: 'Brand Manager Approval',
        status: 'PENDING',
        assignedRole: 'BRAND_MANAGER',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
      {
        id: 'step-1-2',
        stepNumber: 2,
        stepName: 'Finance Director Approval',
        status: 'PENDING',
        assignedRole: 'FINANCE_DIRECTOR',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
    ],
  },
  {
    id: 'wf-2',
    type: 'OTB_APPROVAL',
    referenceType: 'OTB_PLAN',
    referenceId: 'otb-2',
    status: 'IN_PROGRESS',
    currentStep: 1,
    totalSteps: 2,
    initiatedById: 'user-2',
    initiatedBy: mockUsers[1],
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-05'),
    steps: [
      {
        id: 'step-2-1',
        stepNumber: 1,
        stepName: 'Brand Manager Review',
        status: 'PENDING',
        assignedRole: 'BRAND_MANAGER',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
      {
        id: 'step-2-2',
        stepNumber: 2,
        stepName: 'Planning Director Approval',
        status: 'PENDING',
        assignedRole: 'PLANNING_DIRECTOR',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
    ],
  },
  {
    id: 'wf-3',
    type: 'SKU_APPROVAL',
    referenceType: 'SKU_PROPOSAL',
    referenceId: 'sku-2',
    status: 'IN_PROGRESS',
    currentStep: 1,
    totalSteps: 2,
    initiatedById: 'user-4',
    initiatedBy: mockUsers[3],
    createdAt: new Date('2024-11-18'),
    updatedAt: new Date('2024-11-18'),
    steps: [
      {
        id: 'step-3-1',
        stepNumber: 1,
        stepName: 'OTB Planner Review',
        status: 'PENDING',
        assignedRole: 'PLANNER',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
      {
        id: 'step-3-2',
        stepNumber: 2,
        stepName: 'Brand Manager Approval',
        status: 'PENDING',
        assignedRole: 'BRAND_MANAGER',
        actionById: null,
        actionBy: null,
        actionAt: null,
        comments: null,
      },
    ],
  },
  {
    id: 'wf-4',
    type: 'BUDGET_APPROVAL',
    referenceType: 'BUDGET',
    referenceId: 'budget-1',
    status: 'APPROVED',
    currentStep: 2,
    totalSteps: 2,
    initiatedById: 'user-2',
    initiatedBy: mockUsers[1],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-15'),
    steps: [
      {
        id: 'step-4-1',
        stepNumber: 1,
        stepName: 'Brand Manager Approval',
        status: 'APPROVED',
        assignedRole: 'BRAND_MANAGER',
        actionById: 'user-3',
        actionBy: mockUsers[2],
        actionAt: new Date('2024-10-10'),
        comments: 'Approved - budget allocation looks good',
      },
      {
        id: 'step-4-2',
        stepNumber: 2,
        stepName: 'Finance Director Approval',
        status: 'APPROVED',
        assignedRole: 'FINANCE_DIRECTOR',
        actionById: 'user-1',
        actionBy: mockUsers[0],
        actionAt: new Date('2024-10-15'),
        comments: 'Final approval granted',
      },
    ],
  },
];

// =====================
// NOTIFICATIONS
// =====================

export const mockNotifications = [
  {
    id: 'notif-1',
    userId: 'user-3',
    type: 'APPROVAL_REQUEST',
    title: 'Budget Approval Required',
    message: 'Nike SS25 Hanoi budget is pending your approval',
    isRead: false,
    readAt: null,
    link: '/budget/budget-3',
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'notif-2',
    userId: 'user-3',
    type: 'APPROVAL_REQUEST',
    title: 'OTB Plan Review Required',
    message: 'Adidas SS25 HCM OTB plan needs your review',
    isRead: false,
    readAt: null,
    link: '/otb-analysis/otb-2',
    createdAt: new Date('2024-11-05'),
  },
  {
    id: 'notif-3',
    userId: 'user-2',
    type: 'APPROVAL_REQUEST',
    title: 'SKU Proposal Review',
    message: 'Nike SS25 SKU Batch 2 is submitted for review',
    isRead: false,
    readAt: null,
    link: '/sku-proposal/sku-2',
    createdAt: new Date('2024-11-18'),
  },
  {
    id: 'notif-4',
    userId: 'user-2',
    type: 'APPROVAL_COMPLETED',
    title: 'Budget Approved',
    message: 'Nike SS25 HCM budget has been approved',
    isRead: true,
    readAt: new Date('2024-10-15'),
    link: '/budget/budget-1',
    createdAt: new Date('2024-10-15'),
  },
  {
    id: 'notif-5',
    userId: 'user-4',
    type: 'APPROVAL_COMPLETED',
    title: 'SKU Proposal Approved',
    message: 'Nike SS25 SKU Batch 1 has been approved',
    isRead: true,
    readAt: new Date('2024-11-15'),
    link: '/sku-proposal/sku-1',
    createdAt: new Date('2024-11-15'),
  },
];

// =====================
// DASHBOARD STATS
// =====================

export const mockDashboardStats = {
  brandsCount: mockBrands.length,
  categoriesCount: 12,
  locationsCount: mockLocations.length,
  usersCount: mockUsers.length,
  currentSeason: mockSeasons[0],

  budgetSummary: {
    total: mockBudgets.length,
    draft: mockBudgets.filter(b => b.status === 'DRAFT').length,
    submitted: mockBudgets.filter(b => b.status === 'SUBMITTED').length,
    approved: mockBudgets.filter(b => b.status === 'APPROVED').length,
    totalAmount: mockBudgets.reduce((sum, b) => sum + b.totalBudget, 0),
  },

  otbSummary: {
    total: mockOTBPlans.length,
    draft: mockOTBPlans.filter(o => o.status === 'DRAFT').length,
    submitted: mockOTBPlans.filter(o => o.status === 'SUBMITTED').length,
    approved: mockOTBPlans.filter(o => o.status === 'APPROVED').length,
  },

  skuSummary: {
    total: mockSKUProposals.length,
    draft: mockSKUProposals.filter(s => s.status === 'DRAFT').length,
    submitted: mockSKUProposals.filter(s => s.status === 'SUBMITTED').length,
    approved: mockSKUProposals.filter(s => s.status === 'APPROVED').length,
  },

  pendingApprovals: mockWorkflows.filter(w => w.status === 'IN_PROGRESS').length,
};

// =====================
// HELPER FUNCTIONS
// =====================

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND',
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatNumber(num: number): string {
  return new Intl.NumberFormat('vi-VN').format(num);
}

export function formatPercent(num: number): string {
  return `${num.toFixed(1)}%`;
}
