// Enums - định nghĩa độc lập, không phụ thuộc @prisma/client
// Để cả FE và BE có thể sử dụng

export enum UserRole {
  ADMIN = 'ADMIN',
  FINANCE_HEAD = 'FINANCE_HEAD',
  FINANCE_USER = 'FINANCE_USER',
  BRAND_MANAGER = 'BRAND_MANAGER',
  BRAND_PLANNER = 'BRAND_PLANNER',
  MERCHANDISE_LEAD = 'MERCHANDISE_LEAD',
  BOD_MEMBER = 'BOD_MEMBER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
}

export enum BudgetStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REVISED = 'REVISED',
  REJECTED = 'REJECTED',
}

export enum Gender {
  MEN = 'MEN',
  WOMEN = 'WOMEN',
  UNISEX = 'UNISEX',
  KIDS = 'KIDS',
}

export enum OTBPlanStatus {
  DRAFT = 'DRAFT',
  SYSTEM_PROPOSED = 'SYSTEM_PROPOSED',
  USER_PROPOSED = 'USER_PROPOSED',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REVISED = 'REVISED',
  FINAL = 'FINAL',
}

export enum OTBVersionType {
  V0_SYSTEM = 'V0_SYSTEM',
  V1_USER = 'V1_USER',
  V2_ADJUSTED = 'V2_ADJUSTED',
  V3_REVIEWED = 'V3_REVIEWED',
  VA_APPROVED = 'VA_APPROVED',
  VF_FINAL = 'VF_FINAL',
  REVISED = 'REVISED',
}

export enum SKUProposalStatus {
  DRAFT = 'DRAFT',
  VALIDATING = 'VALIDATING',
  VALIDATED = 'VALIDATED',
  ENRICHING = 'ENRICHING',
  ENRICHED = 'ENRICHED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REVISED = 'REVISED',
}

export enum SKUValidationStatus {
  PENDING = 'PENDING',
  VALID = 'VALID',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}

export enum WorkflowType {
  BUDGET_APPROVAL = 'BUDGET_APPROVAL',
  OTB_APPROVAL = 'OTB_APPROVAL',
  SKU_APPROVAL = 'SKU_APPROVAL',
}

export enum WorkflowStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum WorkflowStepStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
}

export enum NotificationType {
  BUDGET_SUBMITTED = 'BUDGET_SUBMITTED',
  BUDGET_APPROVED = 'BUDGET_APPROVED',
  BUDGET_REJECTED = 'BUDGET_REJECTED',
  OTB_SUBMITTED = 'OTB_SUBMITTED',
  OTB_APPROVED = 'OTB_APPROVED',
  OTB_REJECTED = 'OTB_REJECTED',
  SKU_SUBMITTED = 'SKU_SUBMITTED',
  SKU_APPROVED = 'SKU_APPROVED',
  SKU_REJECTED = 'SKU_REJECTED',
  WORKFLOW_ASSIGNED = 'WORKFLOW_ASSIGNED',
  WORKFLOW_REMINDER = 'WORKFLOW_REMINDER',
  SLA_WARNING = 'SLA_WARNING',
  SLA_BREACHED = 'SLA_BREACHED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  AI_INSIGHT = 'AI_INSIGHT',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export const LOCATION_TYPES = ['STORE', 'OUTLET', 'ONLINE'] as const;
export type LocationType = (typeof LOCATION_TYPES)[number];
